language: android
jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.0
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

licenses:
  - android-sdk-license-.+

before_script:
    - gradle -v

script:
  ./gradlew clean build --stacktrace